### PR TITLE
🐛 Fix `Reset Project Cache` command

### LINKED ISSUE #1258: Ensure the `Reset Project Cache` command actually works

### PR DESCRIPTION
**Pull request by misode**
- Fixes #1258

The issue was caused because the `vanilla-datapack` and `vanilla-mcdoc` dependencies relied on the downloader setting the `out.cacheUri` field. This did not happen when memory cache was found (because only the raw buffer was stored in the memory cache).

The memory cache is only intended to last 15 seconds, but due to a logic error, memory cache entries never expired.

### CODE REVIEW

File: packages/core/src/service/Downloader.ts [hunk 1]
```diff
@@ -31,11 +35,14 @@ export class Downloader {
 	): Promise<R | undefined> {
 		const { id, cache, uri, options, transformer, ttl } = job
 		if (ttl && this.#memoryCache.has(uri)) {
-			const { buffer, time } = this.#memoryCache.get(uri)!
-			if (time <= performance.now() + ttl) {
+			const memoryCacheEntry = this.#memoryCache.get(uri)!
```
Comment (TheAfroOfDoom) [inline packages/core/src/service/Downloader.ts:38]: annoying that we need the non-null assertion here. I see that it can't be undefined because of the `has` above

**Review by TheAfroOfDoom — APPROVED** [review]
so this bug is why we were always recommending we delete the cache manually? with `Open Cache Folder`

File: packages/core/src/service/Downloader.ts (hunk 1 above)
Comment (misode) [reply packages/core/src/service/Downloader.ts:38]: Yeah bit of a typescript quirk, but not that important. We have this pattern in a couple of other places.

**Comment by misode** [comment]
> so this bug is why we were always recommending we delete the cache manually? with `Open Cache Folder`

Yes, hopefully that won't be necessary anymore. We'll have to monitor when people get symbol cache issues and check if the command works fine for them.

File: packages/core/src/service/Downloader.ts [hunk 2]
```diff
@@ -31,11 +35,14 @@ export class Downloader {
...
+			const { buffer, time, cacheUri, checksum } = memoryCacheEntry
+			if (performance.now() <= time + ttl) {
```
Comment (SPGoding) [inline packages/core/src/service/Downloader.ts:40]: What was I smoking lol

**Review by SPGoding — APPROVED** [review]
