### PR TITLE
🐛 Fix how locales with subtags are handled

### LINKED ISSUE #1134: Make `loadLocale()` fall back gracefully when locale has subtags
Current Behavior:

* Call `loadLocale('en-us')`
* It throws an exception because there is no language file `en-us.js`

Expected Behavior:

* Call `loadLocale('en-us')`
* It should try to load `en-us.js` and fail
* It should try to load `en.js` (with `-us` subtag removed) and succeed

### PR DESCRIPTION
**Pull request by SPGoding**
Fixes #1134.

### CODE REVIEW

File: packages/locales/src/index.ts [hunk 1]
```diff
@@ -37,11 +37,33 @@ export function localeQuote(content: string) {
...
+		// Most likely due to unknown locale.
+
+		const lastDashIndex = locale.lastIndexOf('-')
+		if (lastDashIndex === -1) {
+			// The locale has no subtags. No more locales to try.
+			throw e
+		}
+
+		// Try again with the rightmost subtag removed.
+		return loadLocale(locale.slice(0, lastDashIndex), dry)
```
Comment (misode) [inline packages/locales/src/index.ts:66]: This makes me a bit nervous but I can't see any way this could get in an infinite loop, so it should be fine.

**Review by misode — APPROVED** [review]

**Review by TheAfroOfDoom — APPROVED** [review]
