### PR TITLE
:bug: Fix selector parser being too strict in /say

### LINKED ISSUE #1304: `/say` selector parser is too strict
It shouldn't error for cases like this. Reference the decompiled code to see how Minecraft parses this.

image

### PR DESCRIPTION
**Pull request by Calverin**
Fixes #1304

### CODE REVIEW

File: packages/java-edition/src/mcfunction/parser/argument.ts [hunk 1]
```diff
@@ -679,10 +679,16 @@ function resourceOrInline(category: core.FileCategory) {
...
 
-function selectorPrefix(): core.InfallibleParser<core.LiteralNode> {
+function selectorPrefix(ignoreInvalidPrefix: boolean): core.InfallibleParser<core.LiteralNode> {
 	return (src: core.Source, ctx: core.ParserContext): core.LiteralNode => {
 		const start = src.cursor
-		const value = src.readUntil(' ', '\r', '\n', '[')
+		let value: string
+		if (ignoreInvalidPrefix) {
+			value = src.peek(0, 2)
+			src.skip(2)
```
Comment (TheAfroOfDoom) [inline packages/java-edition/src/mcfunction/parser/argument.ts:688]: i think this will do the same thing for you:

```suggestion
			value = src.read(2)
```

Comment (Calverin) [reply packages/java-edition/src/mcfunction/parser/argument.ts:688]: `src.read()` doesn't accept any arguments, I had thought this would work as well but it just doesn't exist. Mandela effect something something...

**Review by MulverineX — APPROVED** [review]

**Review by misode — APPROVED** [review]
