### PR TITLE
Do not send documents for archive urls (Fixes #1745)

### LINKED ISSUE #1745: Language server reports diagnostics for source archives
Hey, I started working on a plugin for JetBrains that uses this LSP: https://github.com/JulianVennen/spyglass-mc-jetbrains

While working on that, I noticed numerous errors in my IntelliJ log that looked something like this:
```
2025-02-04 18:47:42,428 [  10441]   WARN - #c.i.p.l.a.LspServerDescriptor - Unexpected URI scheme: archive://vanilla-mcdoc.tar.gz/java/server/world/entity/mob/breedable/tamable.mcdoc
```

After enabling debug logging which outputs all LSP messages, the following appeared:
```
2025-02-04 18:47:42,428 [  10441]   FINE - #c.i.p.l.i.c.Lsp4jServerConnector - <-- SpyglassLspServerDescriptor@towers: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"archive://vanilla-mcdoc.tar.gz/java/server/world/entity/mob/fish.mcdoc"}}
```

Spyglass appears to be reporting diagnostics for files inside the vanilla-mcdoc.tar.gz and mcmeta.tar.gz. Obviously, files inside these are not part of the project I have opened in my IDE, so it makes sense that IntelliJ logs an error in that case.

### PR DESCRIPTION
**Pull request by JulianVennen**
Fixes #1745

### CODE REVIEW

**Review by SPGoding — APPROVED** [review]

File: packages/language-server/src/server.ts [hunk 1]
```diff
@@ -88,6 +88,10 @@ connection.onInitialize(async (params) => {
 			},
 		})
 		service.project.on('documentErrored', async ({ errors, uri, version }) => {
+			if (!uri.startsWith('file://')) {
```
Comment (misode) [inline packages/language-server/src/server.ts:91]: Is it a good idea to explicitly check for `file` rather than filter out `archive` explicitly? Are we sure this won't break stuff like remote ssh, live share, or others?

Comment (JulianVennen) [reply packages/language-server/src/server.ts:91]: Both the intellij built in lsp client and lsp4intellij check explicitly for file://. If there's a case where vscode accepts other urls I can check for archive:// instead

Comment (SPGoding) [reply packages/language-server/src/server.ts:91]: Afaik VS Code uses the `untitled:` URI scheme for new files that are not saved on disk

**Review by misode — APPROVED** [review]

**Review by SPGoding — APPROVED** [review]
