### PR TITLE
🐛 Use custom file tree walker instead of globby

### LINKED ISSUE #1572: Cannot find `pack.mcmeta` when projectRoot is "complex"
Example project root that doesn't work: `file:///c%3A/Users/foo/AppData/Roaming/.minecraft/saves/%C2%A7a%C2%A7lVersion%201.21%20%C2%A74%C2%A7l%5B4.5%5D%C2%A77/datapacks/bar/`, which after percent decoding is `file:///c:/Users/foo/AppData/Roaming/.minecraft/saves/§a§lVersion 1.21 §4§l[4.5]§7/datapacks/bar/`

Maybe all those percent encoding messed something up?

### PR DESCRIPTION
**Pull request by SPGoding**
Fix #1572.

### CODE REVIEW

File: packages/java-edition/src/index.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ export const initialize: core.ProjectInitializer = async (ctx) => {
 		const searched = new Set<string>()
 		for (let depth = 0; depth <= 2; depth += 1) {
 			for (const projectRoot of projectRoots) {
-				const files = await externals.fs.getAllFiles(projectRoot, depth + 1)
+				const files = await core.fileUtil.getAllFiles(externals, projectRoot, depth + 1)
```
Comment (misode) [inline packages/java-edition/src/index.ts:47]: The `getAllFiles` function here is called multiple times, each time increasing its depth, therefore repeating the directory walk. It may be possible to optimize this in the future.

**Review by misode — APPROVED** [review]
Testing this, I can confirm it fixes the "cannot find pack.mcmeta" issue.

However it does not fix the more general issue where symbols are not found. After some debugging I realized this is a completely separate problem, so I'll create a new issue for it.

File: packages/java-edition/src/index.ts (hunk 1 above)
Comment (SPGoding) [reply packages/java-edition/src/index.ts:47]: I think this wouldn't be necessary if we make `getAllFiles()` breadth-first instead of depth-first, so that the earliest `pack.mcmeta` file would be the shallowest, and we can limit depth to `2` directly.

Comment (misode) [reply packages/java-edition/src/index.ts:47]: The point would also be to prevent checking depth 2 if there is a valid pack.mcmeta at depth 1

Comment (SPGoding) [reply packages/java-edition/src/index.ts:47]: Hmm. It could be made into a breadth-first generator?

Comment (misode) [reply packages/java-edition/src/index.ts:47]: But imo that isn't necessary to be done now. This will most likely already be more efficient than globby. So feel free to merge if you are fine with this.

Comment (SPGoding) [reply packages/java-edition/src/index.ts:47]: Yeah. I also think if it were implemented it wouldn't necessarily be an optimization. We'd just be trading more memory consumption for less IO calls.
