### PR TITLE
🐛 Fix data append and prepend using list definition instead of list item for type checking

### LINKED ISSUE #1403: Incorrect type indexing with `data modify ... insert|prepend|append`
```
data modify block ~ ~ ~ Items append value {id:"book",count:1}
```

### PR DESCRIPTION
**Pull request by NeunEinser**
Fixes #1403

With this, the list item definition is used instead for append and prepend.

We probably want to verify that the item returned by the path is actually a list. The type checking for the Nbt node is completely disabled when no list-like is found at the index.

Similarly, there is currently no error when trying to use data modify merge on anything else than a compound.

### CODE REVIEW

**Comment by NeunEinser** [comment]
Tuples don't really make sense to be appended or prepended, they should always have a fixed size. The only case I suppose would be sth like `([string] | [string, int])` where you could technically append an int and it would still be valid.

I think it's fine to just not support this though.

File: packages/java-edition/src/mcfunction/checker/index.ts [hunk 1]
```diff
@@ -242,6 +248,33 @@ function nbtChecker(
 	}
 }
 
+function getListLikeChild(typeDef: mcdoc.McdocType): mcdoc.McdocType | undefined {
```
Comment (misode) [inline packages/java-edition/src/mcfunction/checker/index.ts:251]: Should this be changed to take a `SimplifiedMcdocType`?

**Review by misode — APPROVED** [review]
Clean solution, I like it!

File: packages/java-edition/src/mcfunction/checker/index.ts [hunk 2]
```diff
@@ -201,8 +201,14 @@ function nbtChecker(
...
 		if (indexedBy) {
-			if (NbtPathNode.is(indexedBy) && indexedBy.children[0].endTypeDef) {
-				nbt.checker.typeDefinition(indexedBy.children[0].endTypeDef)(tag, ctx)
+			if (NbtPathNode.is(indexedBy)) {
+				let typeDef: mcdoc.McdocType | undefined = indexedBy.children[0].endTypeDef
+				if (typeDef && node.properties.isListIndex) {
+					typeDef = getListLikeChild(typeDef)
+				}
+				if (typeDef) {
+					nbt.checker.typeDefinition(typeDef)(tag, ctx)
```
Comment (misode) [inline packages/java-edition/src/mcfunction/checker/index.ts:210]: This was a bug before this PR too, but this call should pass `isMerge`

File: packages/java-edition/src/mcfunction/checker/index.ts (hunk 1 above)
Comment (NeunEinser) [reply packages/java-edition/src/mcfunction/checker/index.ts:251]: The return value no, because the item of a list is not simplified. The parameter could be though.

**Comment by SPGoding** [comment]
Nice
